using System.Text.Json;
using TypeSafeSdk;
return await new TypeSafeCli().RunAsync(args);
internal sealed class TypeSafeCli
{
 public async Task<int> RunAsync(string[] args){if(args.Length==0||Has(args,"--help","-h")){Help();return 0;}try{var o=Options(Has(args,"--live"),Get(args,"--model"));await using var c=new TypeSafeClient(o);return args[0].ToLowerInvariant() switch{"classify"=>await Classify(c,args),"noul"=>await Noul(c,args),"score"=>await Score(c,args),"evaluate"=>await Evaluate(c,args),"models"=>await Models(c),"validate"=>Validate(args),"config"=>Config(o),_=>Fail("Unknown command. Use --help.")};}catch(TypeSafeApiException e){Console.Error.WriteLine($"TypeSafe API error ({e.StatusCode}): {e.Message}");return 2;}catch(Exception e){Console.Error.WriteLine($"Error: {e.Message}");return 1;}}
 static TypeSafeOptions Options(bool live,string? model){var o=TypeSafeOptions.FromEnvironment();if(model is not null)o.DefaultModel=model;o.Simulator=!live;if(live)o.ApiKey=TypeSafeApiKeyLoader.LoadFromFile(Environment.GetEnvironmentVariable("TYPESAFE_API_KEY_FILE")??@"C:\Users\mifma\Documents\CodeSandbox\TypeSafeApiKey.txt");return o;}
 static async Task<int> Classify(TypeSafeClient c,string[] a){var values=(Get(a,"--choices")??"billing,technical,other").Split(',',StringSplitOptions.TrimEntries|StringSplitOptions.RemoveEmptyEntries);var r=await c.SystemOneAsync(new{document=Text(a)},Choice.Create(values));Print(new{category=r.Choices.GetValueOrDefault("category")?.Choice,confidence=r.Choices.GetValueOrDefault("category")?.Confidence,r.Model,r.Usage});return 0;}
 static async Task<int> Noul(TypeSafeClient c,string[] a){var q=new Dictionary<string,object>{{"result",new NoulSchema(Get(a,"--question")??"Does this text satisfy the question?").ToApiQuestion()}};var r=await c.SystemOneAsync(Text(a),q,Get(a,"--model"),retry:null);Print(new{noul=r.Nouls.GetValueOrDefault("result")?.Noul,r.Model,r.Usage});return 0;}
 static async Task<int> Score(TypeSafeClient c,string[] a){var levels=(Get(a,"--levels")??"low,medium,high").Split(',',StringSplitOptions.TrimEntries|StringSplitOptions.RemoveEmptyEntries);if(levels.Length<2)throw new ArgumentException("--levels requires at least two values.");var q=new Dictionary<string,object>{{"result",new ScoreSchema(Get(a,"--question")??"How should this be rated?",levels).ToApiQuestion()}};var r=await c.SystemOneAsync(Text(a),q,Get(a,"--model"),retry:null);var x=r.Scores.GetValueOrDefault("result");Print(new{score=x?.Score,x?.Legend,x?.Probabilities,x?.Confidence,r.Model,r.Usage});return 0;}
 static async Task<int> Evaluate(TypeSafeClient c,string[] a){using var s=JsonDocument.Parse(Get(a,"--state")??throw new ArgumentException("--state required."));using var q=JsonDocument.Parse(Get(a,"--questions")??throw new ArgumentException("--questions required."));var r=await c.SystemOneAsync(s.RootElement.Clone(),q.RootElement.Clone(),Get(a,"--model"),retry:null);Print(new{r.Model,r.Answers,r.Usage});return 0;}
 static async Task<int> Models(TypeSafeClient c){Print(await c.Models.ListAsync());return 0;} static int Validate(string[] a){var x=(Get(a,"--choices")??Text(a)).Split(',',StringSplitOptions.TrimEntries|StringSplitOptions.RemoveEmptyEntries);_=Choice.Create(x);Console.WriteLine($"Valid Choice schema: {string.Join(", ",x)}");return 0;}static int Config(TypeSafeOptions o){Print(new{o.Endpoint,o.DefaultModel,o.Simulator,HasApiKey=!string.IsNullOrWhiteSpace(o.ApiKey)});return 0;}
 static string Text(string[] a)=>string.Join(' ',a.Skip(1).Where((x,i)=>!x.StartsWith("--")&&(i==0||!a[i].StartsWith("--"))));static string? Get(string[] a,string n){var i=Array.FindIndex(a,x=>x.Equals(n,StringComparison.OrdinalIgnoreCase));return i>=0&&i+1<a.Length?a[i+1]:null;}static bool Has(IEnumerable<string>a,params string[]x)=>a.Any(v=>x.Contains(v,StringComparer.OrdinalIgnoreCase));static void Print(object x)=>Console.WriteLine(JsonSerializer.Serialize(x,new JsonSerializerOptions{WriteIndented=true}));static int Fail(string x){Console.Error.WriteLine(x);return 1;}
 static void Help()=>Console.WriteLine("TypeSafe CLI\n classify <text> [--choices a,b,c] [--live] [--model name]\n noul <text> --question \"Is urgent?\" [--live]\n score <text> --question \"How urgent?\" --levels low,medium,high [--live]\n evaluate --state '<json>' --questions '<json>' [--live]\n models --live\n validate --choices a,b,c\n config [--live]\n\nWithout --live uses the local simulator.");
}
