namespace PollenRobotics.Net.Core.Robots;

/// <summary>
/// The joint models for every robot this SDK supports.
/// </summary>
/// <remarks>
/// <para>
/// These are transcribed from the published Pollen Robotics documentation, not measured from
/// hardware. Where the documentation gives a limit it is used verbatim; where it does not, the
/// value is a conservative guess and is marked as such in the comment above it. See
/// <c>docs/joint-models.md</c> for the source of each number.
/// </para>
/// <para>
/// The order of each list is the wire order, and <see cref="RobotDescription"/> asserts that the
/// declared indices agree with it. Never resolve a joint by a hard-coded integer - ask for it by
/// name, because a variant with a different joint count shifts every index after the one that
/// changed.
/// </para>
/// </remarks>
public static class RobotCatalog
{
    /// <summary>
    /// Reachy Mini: body yaw, six Stewart-platform neck motors, two antennas. Nine actuators.
    /// </summary>
    /// <remarks>
    /// The wire order matches the daemon <c>head_joint_positions</c> field, which puts body yaw at
    /// index 0 and the six neck branches at 1..6, then reports the antennas separately in
    /// <c>antennas_joint_positions</c> as [right, left]. This description flattens both into one
    /// vector, appending the antennas after the neck.
    /// </remarks>
    public static RobotDescription ReachyMini { get; } = new(
        RobotKind.ReachyMini,
        "Reachy Mini",
        [
            // Documented limit: body yaw is constrained to +/-160 degrees.
            JointDescriptor.Degrees("body.yaw", 0, -160, 160),

            // The six Stewart branches are not commanded individually by user code - the head pose
            // is. The published documentation does not state a per-branch limit, so these are a
            // deliberately wide guess; the pose-level limits below are the ones that actually bind.
            JointDescriptor.Degrees("neck.branch_1", 1, -90, 90),
            JointDescriptor.Degrees("neck.branch_2", 2, -90, 90),
            JointDescriptor.Degrees("neck.branch_3", 3, -90, 90),
            JointDescriptor.Degrees("neck.branch_4", 4, -90, 90),
            JointDescriptor.Degrees("neck.branch_5", 5, -90, 90),
            JointDescriptor.Degrees("neck.branch_6", 6, -90, 90),

            // Antennas are continuous in hardware but a full turn tangles the cabling; the SDK
            // keeps them inside one revolution.
            JointDescriptor.Degrees("antenna.right", 7, -180, 180),
            JointDescriptor.Degrees("antenna.left", 8, -180, 180),
        ]);

    /// <summary>
    /// MicroDuck: fifteen servos - two five-DOF legs, a two-DOF neck, a head joint and a beak.
    /// </summary>
    /// <remarks>
    /// The daemon documentation states the servo count and the 50 Hz loop rate but does not publish
    /// a per-joint name table, so the names below follow the biped convention used by the open
    /// hardware description and the limits are conservative. Treat them as a starting point to be
    /// corrected against <c>robotctl monitor</c> output on a real duck.
    /// </remarks>
    public static RobotDescription MicroDuck { get; } = new(
        RobotKind.MicroDuck,
        "MicroDuck",
        [
            JointDescriptor.Degrees("left.hip_yaw", 0, -45, 45),
            JointDescriptor.Degrees("left.hip_roll", 1, -35, 35),
            JointDescriptor.Degrees("left.hip_pitch", 2, -90, 60),
            JointDescriptor.Degrees("left.knee", 3, -10, 130),
            JointDescriptor.Degrees("left.ankle_pitch", 4, -70, 70),

            JointDescriptor.Degrees("right.hip_yaw", 5, -45, 45),
            JointDescriptor.Degrees("right.hip_roll", 6, -35, 35),
            JointDescriptor.Degrees("right.hip_pitch", 7, -90, 60),
            JointDescriptor.Degrees("right.knee", 8, -10, 130),
            JointDescriptor.Degrees("right.ankle_pitch", 9, -70, 70),

            JointDescriptor.Degrees("neck.pitch", 10, -40, 45),
            JointDescriptor.Degrees("neck.yaw", 11, -90, 90),
            JointDescriptor.Degrees("head.pitch", 12, -30, 30),
            JointDescriptor.Degrees("head.roll", 13, -25, 25),
            JointDescriptor.Degrees("beak", 14, 0, 45),
        ]);

    /// <summary>
    /// Reachy 2: two 7-DOF arms, a three-DOF Orbita neck, two antennas and two grippers.
    /// </summary>
    /// <remarks>
    /// Joint names match the dotted paths the Python SDK exposes (<c>r_arm.shoulder.pitch</c> and
    /// friends) so that code generated by the wizard reads the same in both languages. The mobile
    /// base is not a joint chain and is modelled separately.
    /// </remarks>
    public static RobotDescription Reachy2 { get; } = new(
        RobotKind.Reachy2,
        "Reachy 2",
        [
            JointDescriptor.Degrees("r_arm.shoulder.pitch", 0, -180, 90),
            JointDescriptor.Degrees("r_arm.shoulder.roll", 1, -180, 10),
            JointDescriptor.Degrees("r_arm.elbow.yaw", 2, -90, 90),
            JointDescriptor.Degrees("r_arm.elbow.pitch", 3, -125, 0),
            JointDescriptor.Degrees("r_arm.wrist.roll", 4, -45, 45),
            JointDescriptor.Degrees("r_arm.wrist.pitch", 5, -45, 45),
            JointDescriptor.Degrees("r_arm.wrist.yaw", 6, -45, 45),

            JointDescriptor.Degrees("l_arm.shoulder.pitch", 7, -180, 90),
            JointDescriptor.Degrees("l_arm.shoulder.roll", 8, -10, 180),
            JointDescriptor.Degrees("l_arm.elbow.yaw", 9, -90, 90),
            JointDescriptor.Degrees("l_arm.elbow.pitch", 10, -125, 0),
            JointDescriptor.Degrees("l_arm.wrist.roll", 11, -45, 45),
            JointDescriptor.Degrees("l_arm.wrist.pitch", 12, -45, 45),
            JointDescriptor.Degrees("l_arm.wrist.yaw", 13, -45, 45),

            JointDescriptor.Degrees("head.neck.roll", 14, -45, 45),
            JointDescriptor.Degrees("head.neck.pitch", 15, -45, 45),
            JointDescriptor.Degrees("head.neck.yaw", 16, -90, 90),

            JointDescriptor.Degrees("head.r_antenna", 17, -150, 150),
            JointDescriptor.Degrees("head.l_antenna", 18, -150, 150),

            JointDescriptor.Degrees("r_arm.gripper", 19, -5, 130),
            JointDescriptor.Degrees("l_arm.gripper", 20, -5, 130),
        ]);

    /// <summary>Looks a description up by robot family.</summary>
    public static RobotDescription For(RobotKind kind) => kind switch
    {
        RobotKind.ReachyMini => ReachyMini,
        RobotKind.MicroDuck => MicroDuck,
        RobotKind.Reachy2 => Reachy2,
        _ => throw new ArgumentOutOfRangeException(nameof(kind), kind, "Unknown robot kind."),
    };

    /// <summary>Every description, in the order the pickers list them.</summary>
    public static IReadOnlyList<RobotDescription> All { get; } = [ReachyMini, MicroDuck, Reachy2];
}
