<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <RootNamespace>Unitree.Net.TemplateCheck</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Unitree.Net.Wizard.Core\Unitree.Net.Wizard.Core.csproj" />
  </ItemGroup>

</Project>
