using System.Text.Json;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Media;
using System.Windows.Media.Effects;
using TypeSafeSdk;
namespace TypeSafe.BoardGames;
public partial class MainWindow : Window
{
 private readonly AppConfig _config; private readonly TypeSafeClient _client; private string _game="Tic Tac Toe"; private char[,] _board=new char[3,3]; private int _rows=3,_cols=3,_playerScore,_aiScore,_drawScore; private bool _busy,_finished;
 private const char Player='X',Ai='O',Empty='.';
 private static readonly Brush PlayerBrush=new SolidColorBrush(Color.FromRgb(30,144,255)); private static readonly Brush AiBrush=new SolidColorBrush(Color.FromRgb(235,45,65)); private static readonly Brush OthelloPlayerBrush=new SolidColorBrush(Color.FromRgb(77,166,255)); private static readonly Brush OthelloAiBrush=new SolidColorBrush(Color.FromRgb(255,62,77)); private static readonly Brush LegalMoveBrush=new SolidColorBrush(Color.FromRgb(102,255,190));
 public MainWindow(){InitializeComponent();_config=LoadConfig();_client=new TypeSafeClient(new TypeSafeOptions{ApiKey=_config.ApiKey,Endpoint=_config.Endpoint,DefaultModel=_config.DefaultModel,Simulator=_config.UseSimulator});PlayerLabel.Text=PlayerCard.Text=LegendPlayer.Text=$"{_config.PlayerName.ToUpperInvariant()} • PLAYER 1";AiLabel.Text=AiCard.Text=LegendAi.Text=$"{_config.EnemyName.ToUpperInvariant()} • PLAYER 2";ModeText.Text=_config.UseSimulator?"SIMULATOR • LOCAL TACTICS":"TYPESAFE LIVE • LOCAL FALLBACK";StartRound();}
 private static AppConfig LoadConfig(){var p=System.IO.Path.Combine(AppContext.BaseDirectory,"app.config.json");return System.IO.File.Exists(p)?JsonSerializer.Deserialize<AppConfig>(System.IO.File.ReadAllText(p))??new():new();}
 private void UpdatePieceIdentity(){var o=_game=="Othello";var p=o?"◆":"✕";LegendPlayerShape.Text=PlayerCardShape.Text=PlayerScoreShape.Text=p;LegendAiShape.Text=AiCardShape.Text=AiScoreShape.Text="●";LegendPlayerDetail.Text=o?"electric-blue diamond":"electric-blue cross";LegendAiDetail.Text="coral-red disc";}
 private void StartRound(){UpdatePieceIdentity();(_rows,_cols)=_game switch{"Othello"=>(8,8),"Connect Four"=>(6,7),_=>(3,3)};_board=new char[_rows,_cols];for(var r=0;r<_rows;r++)for(var c=0;c<_cols;c++)_board[r,c]=Empty;if(_game=="Othello"){_board[3,3]=Ai;_board[4,4]=Ai;_board[3,4]=Player;_board[4,3]=Player;}_busy=false;_finished=false;GameTitle.Text=_game;GameSubtitle.Text=_game=="Othello"?"Player 1 is electric-blue diamond ◆ • Player 2 is coral-red disc ●.":"Player 1 is electric-blue cross ✕ • Player 2 is coral-red disc ●.";AiNote.Text=$"{_config.EnemyName} is ready. Legal moves are highlighted in mint.";StatusText.Text=$"{_config.PlayerName}, choose a highlighted move.";TurnText.Text="PLAYER 1 TURN";DrawBoard();}
 private void DrawBoard(){Board.Rows=_rows;Board.Columns=_cols;Board.Children.Clear();foreach(var(r,c)in Cells()){var legal=IsLegal(r,c,Player);var piece=_board[r,c];var b=new Button{Tag=(r,c),Content=CreatePieceToken(piece),Margin=new Thickness(2),Padding=new Thickness(0),MinWidth=42,MinHeight=42,Background=new SolidColorBrush(_game=="Othello"?Color.FromRgb(28,108,86):Color.FromRgb(22,38,71)),BorderBrush=legal?LegalMoveBrush:new SolidColorBrush(Color.FromRgb(54,78,122)),BorderThickness=new Thickness(legal?3:1),IsEnabled=!_busy&&!_finished&&legal,ToolTip=legal?"Legal move":""};b.Click+=Cell_Click;Board.Children.Add(b);}}
 private string Piece(char p)=>p==Empty?"":_game=="Othello"?(p==Player?"◆":"●"):(p==Player?"✕":"●"); private Brush PieceBrush(char p)=>p==Player?(_game=="Othello"?OthelloPlayerBrush:PlayerBrush):p==Ai?(_game=="Othello"?OthelloAiBrush:AiBrush):Brushes.Transparent;
 private TextBlock CreatePieceToken(char p){var brush=PieceBrush(p);return new TextBlock{Text=Piece(p),Foreground=brush,FontSize=_game=="Othello"?29:38,FontWeight=FontWeights.Black,HorizontalAlignment=HorizontalAlignment.Center,VerticalAlignment=VerticalAlignment.Center,TextAlignment=TextAlignment.Center,Effect=p==Empty?null:new DropShadowEffect{Color=((SolidColorBrush)brush).Color,BlurRadius=12,ShadowDepth=0,Opacity=.9}};}
 private async void Cell_Click(object s,RoutedEventArgs e){if(s is not Button{Tag:ValueTuple<int,int> cell}||_busy||_finished||!ApplyMove(cell.Item1,cell.Item2,Player))return;await ContinueAfterPlayerAsync();}
 private async Task ContinueAfterPlayerAsync(){DrawBoard();if(FinishOrPass(Player))return;_busy=true;TurnText.Text="PLAYER 2 THINKING";StatusText.Text=$"{_config.EnemyName} is choosing a legal move…";AiNote.Text="Checking tactical wins, blocks, corners, then TypeSafe guidance.";await Task.Delay(220);var legal=LegalMoves(Ai).ToList();if(legal.Count>0){var m=await ChooseAiMoveAsync(legal);ApplyMove(m.r,m.c,Ai);AiNote.Text=$"{_config.EnemyName} played {Notation(m.r,m.c)}. Player 1's turn.";}else AiNote.Text=$"{_config.EnemyName} has no legal move and passes.";_busy=false;if(!FinishOrPass(Ai)){TurnText.Text="PLAYER 1 TURN";StatusText.Text=$"{_config.PlayerName}, your move.";DrawBoard();}}
 private async Task<(int r,int c)> ChooseAiMoveAsync(List<(int r,int c)> legal){var local=BestLocalMove(legal);if(_config.UseSimulator||string.IsNullOrWhiteSpace(_config.ApiKey))return local;try{var options=legal.Select(m=>$"{m.r},{m.c}").ToArray();var response=await _client.SystemOneAsync(new{game=_game,board=SerializeBoard(),legal_moves=options,player="O"},Choice.Create(options));var v=response.Choices.GetValueOrDefault("category")?.Choice?.Split(',');if(v?.Length==2&&int.TryParse(v[0],out var r)&&int.TryParse(v[1],out var c)&&legal.Contains((r,c)))return(r,c);}catch(Exception ex){AiNote.Text=$"Live AI unavailable; local tactics used. {ex.Message}";}return local;}
 private (int r,int c) BestLocalMove(List<(int r,int c)> legal){if(_game!="Othello"){foreach(var m in legal)if(WouldWin(m,Ai))return m;foreach(var m in legal)if(WouldWin(m,Player))return m;}if(_game=="Othello"){var corner=legal.FirstOrDefault(m=>(m.r is 0 or 7)&&(m.c is 0 or 7));return legal.Contains(corner)?corner:legal.OrderByDescending(m=>Flips(m.r,m.c,Ai).Count).First();}return legal.OrderBy(m=>Math.Abs(m.r-(_rows-1)/2.0)+Math.Abs(m.c-(_cols-1)/2.0)).First();}
 private bool WouldWin((int r,int c)m,char p){_board[m.r,m.c]=p;var w=HasLine(p);_board[m.r,m.c]=Empty;return w;} private bool IsLegal(int r,int c,char p)=>_board[r,c]==Empty&&(_game switch{"Othello"=>Flips(r,c,p).Count>0,"Connect Four"=>r==FirstEmptyRow(c),_=>true}); private bool ApplyMove(int r,int c,char p){if(!IsLegal(r,c,p))return false;_board[r,c]=p;if(_game=="Othello")foreach(var(x,y)in Flips(r,c,p))_board[x,y]=p;return true;} private int FirstEmptyRow(int c){for(var r=_rows-1;r>=0;r--)if(_board[r,c]==Empty)return r;return-1;} private List<(int r,int c)> LegalMoves(char p)=>Cells().Where(m=>IsLegal(m.r,m.c,p)).ToList();
 private List<(int r,int c)> Flips(int r,int c,char p){var result=new List<(int,int)>();var enemy=p==Player?Ai:Player;foreach(var(dr,dc)in Directions){var line=new List<(int,int)>();var rr=r+dr;var cc=c+dc;while(In(rr,cc)&&_board[rr,cc]==enemy){line.Add((rr,cc));rr+=dr;cc+=dc;}if(line.Count>0&&In(rr,cc)&&_board[rr,cc]==p)result.AddRange(line);}return result;}
 private bool FinishOrPass(char moved){if(_game!="Othello"&&HasLine(moved)){End(moved==Player?$"{_config.PlayerName} wins!":$"{_config.EnemyName} wins this round",moved);return true;}if(_game=="Othello"&&LegalMoves(Player).Count==0&&LegalMoves(Ai).Count==0){var x=Cells().Count(m=>_board[m.r,m.c]==Player);var o=Cells().Count(m=>_board[m.r,m.c]==Ai);End(x==o?"Othello draw":x>o?$"{_config.PlayerName} wins Othello!":$"{_config.EnemyName} wins Othello",x==o?Empty:x>o?Player:Ai);return true;}if(Cells().All(m=>_board[m.r,m.c]!=Empty)){End("Draw game",Empty);return true;}return false;} private void End(string message,char winner){_finished=true;StatusText.Text=message;TurnText.Text="ROUND COMPLETE";if(winner==Player)PlayerScore.Text=(++_playerScore).ToString();else if(winner==Ai)AiScore.Text=(++_aiScore).ToString();else DrawScore.Text=(++_drawScore).ToString();DrawBoard();}
 private bool HasLine(char p){var n=_game=="Tic Tac Toe"?3:4;foreach(var(r,c)in Cells())foreach(var(dr,dc)in new[]{(0,1),(1,0),(1,1),(1,-1)})if(Enumerable.Range(0,n).All(i=>In(r+dr*i,c+dc*i)&&_board[r+dr*i,c+dc*i]==p))return true;return false;} private IEnumerable<(int r,int c)> Cells(){for(var r=0;r<_rows;r++)for(var c=0;c<_cols;c++)yield return(r,c);} private bool In(int r,int c)=>r>=0&&r<_rows&&c>=0&&c<_cols; private string SerializeBoard()=>string.Join("/",Enumerable.Range(0,_rows).Select(r=>new string(Enumerable.Range(0,_cols).Select(c=>_board[r,c]).ToArray()))); private string Notation(int r,int c)=>$"{(char)('A'+c)}{r+1}"; private static readonly(int dr,int dc)[] Directions=[(-1,-1),(-1,0),(-1,1),(0,-1),(0,1),(1,-1),(1,0),(1,1)];
 private void NewRound_Click(object s,RoutedEventArgs e)=>StartRound(); private void NewGame_Click(object s,RoutedEventArgs e){_playerScore=_aiScore=_drawScore=0;PlayerScore.Text=AiScore.Text=DrawScore.Text="0";StartRound();} private void TicTacToe_Click(object s,RoutedEventArgs e){_game="Tic Tac Toe";NewGame_Click(s,e);} private void Othello_Click(object s,RoutedEventArgs e){_game="Othello";NewGame_Click(s,e);} private void ConnectFour_Click(object s,RoutedEventArgs e){_game="Connect Four";NewGame_Click(s,e);} protected override async void OnClosed(EventArgs e){await _client.DisposeAsync();base.OnClosed(e);} private sealed record AppConfig(string ApiKey="",string Endpoint="https://api.typesafe.ai",string DefaultModel="jev-latest",bool UseSimulator=true,string PlayerName="You",string EnemyName="Jack AI");
}
